# Generated by Django 5.2.6 on 2025-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('ano_publicacion', models.TextField(blank=True, verbose_name='año_publicacion')),
                ('genero', models.CharField(max_length=200, verbose_name='Genero')),
            ],
        ),
    ]
