# Generated by Django 5.2.6 on 2025-09-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='ano_publicacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
